apiVersion: v1
kind: Service
metadata:
  name: ordproc-catalog-service
  labels:
    app: ordproc-catalog-service
spec:
  type: NodePort
  ports:
    - port: 8082
      name: http
  selector:
    app: ordproc-catalog-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordproc-catalog-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordproc-catalog-service
        version: v1
    spec:
      containers:
        - name: ordproc-catalog-service
          image: gandigit/ordproc-catalog-service
          imagePullPolicy: IfNotPresent
          env:
            - name: JDBC_HOST
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: host
            - name: JDBC_PORT
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: port
            - name: JDBC_DB
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: db
            - name: JDBC_ID
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: id
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db2
                  key: pwd
          ports:
            - containerPort: 8082
