apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
parameters:
  resturl: http://20.0.152.128:8080
  restuser: admin
  secretName: heketi-secret
  secretNamespace: kube-system
  volumenameprefix: icp
  volumetype: replicate:3
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate