apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://20.0.152.128:8080"
  restuser: "admin"
  volumetype: replicate:3
  volumenameprefix: "icp"